wandb:
  experiment_name: ''
  project: 'SalientDists Sweeps 03.05 v2'
  entity: 'commute_opt_gnn'

data:
  name: SalientDists
  dataset : 'ZINC'
  c1: None
  c2: None
  c3: None
  d: 5
  train_size: 5000
  val_size: 500
  min_train_nodes: 20
  max_train_nodes: 30
  min_val_nodes: 30
  max_val_nodes: 35
  rewirers: ["aligned_cayley", "cayley", "distance_d_pairs"]
  normalise: False
  seed: 93

model:
  hidden_channels: 8
  num_layers: 5
  drop_prob: 0.0
  global_pool_aggr: global_add_pool
  norm: bn
  approaches: ["only_original", "interleave"]
  seeds: [17, 47, 23]
  
train:
  lr: 0.0001
  warmup: 50
  gamma_decay: 0.95
  num_epochs: 200
  print_every: 10
  train_batch_size: 32
  val_batch_size: 32
  loss_fn: "MSE"

run:
  silent: False